# Generated by Django 4.0.5 on 2022-06-26 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.IntegerField(default=0)),
                ('game', models.CharField(max_length=30)),
                ('attempt', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('progress', models.IntegerField(default=0)),
                ('started_on', models.DateTimeField(verbose_name='date started')),
                ('ended_on', models.DateTimeField(verbose_name='date ended')),
                ('set_mode', models.BooleanField(default=False)),
                ('dupes_clause', models.BooleanField(default=False)),
                ('monotype', models.BooleanField(default=False)),
                ('randomised', models.BooleanField(default=False)),
                ('battle_items', models.BooleanField(default=False)),
                ('level_limit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('nickname', models.CharField(max_length=12)),
                ('location_encountered', models.CharField(max_length=30)),
                ('encountered_on', models.DateTimeField(verbose_name='date encountered')),
                ('caught', models.BooleanField(default=False)),
                ('alive', models.BooleanField(default=True)),
                ('nature', models.CharField(max_length=20)),
                ('shiny', models.BooleanField(default=False)),
                ('in_party', models.BooleanField(default=False)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
